"""Parent accounts consent practice and privacy queues

Revision ID: 20261003_01
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = '20261003_01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('catalog_id', sa.String(length=120), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('scoring_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data_purged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_jobs_parent_id'), 'deletion_jobs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_deletion_jobs_status'), 'deletion_jobs', ['status'], unique=False)
    op.create_table('deletion_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_ledger_subject_hash'), 'deletion_ledger', ['subject_hash'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cognito_sub', sa.String(length=128), nullable=False),
    sa.Column('cognito_username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('first_consent_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub')
    )
    op.create_index(op.f('ix_parents_last_active_at'), 'parents', ['last_active_at'], unique=False)
    op.create_table('privacy_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=36), nullable=False),
    sa.Column('parent_email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_notifications_status'), 'privacy_notifications', ['status'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('notice_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('evidence_reference', sa.String(length=200), nullable=True),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_parent_id'), 'consent_records', ['parent_id'], unique=False)
    op.create_table('parent_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_parent_sessions_expires_at'), 'parent_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_parent_sessions_parent_id'), 'parent_sessions', ['parent_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'request_id', name='uq_practice_request')
    )
    op.create_index(op.f('ix_practice_sessions_child_id'), 'practice_sessions', ['child_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_created_at'), 'practice_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_parent_id'), 'practice_sessions', ['parent_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('activity_version_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('speech_detected', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('started','correct','incorrect','no_speech','technical_error','abandoned','microphone_unavailable')", name='ck_attempt_status'),
    sa.ForeignKeyConstraint(['activity_version_id'], ['activity_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'request_id', name='uq_attempt_request')
    )
    op.create_index(op.f('ix_attempts_created_at'), 'attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_attempts_session_id'), 'attempts', ['session_id'], unique=False)
    op.create_table('speech_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'mode', name='uq_speech_check')
    )
    op.create_index(op.f('ix_speech_checks_attempt_id'), 'speech_checks', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speech_checks_attempt_id'), table_name='speech_checks')
    op.drop_table('speech_checks')
    op.drop_index(op.f('ix_attempts_session_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_created_at'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_practice_sessions_parent_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_created_at'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_child_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_parent_sessions_parent_id'), table_name='parent_sessions')
    op.drop_index(op.f('ix_parent_sessions_expires_at'), table_name='parent_sessions')
    op.drop_table('parent_sessions')
    op.drop_index(op.f('ix_consent_records_parent_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_privacy_notifications_status'), table_name='privacy_notifications')
    op.drop_table('privacy_notifications')
    op.drop_index(op.f('ix_parents_last_active_at'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_deletion_ledger_subject_hash'), table_name='deletion_ledger')
    op.drop_table('deletion_ledger')
    op.drop_index(op.f('ix_deletion_jobs_status'), table_name='deletion_jobs')
    op.drop_index(op.f('ix_deletion_jobs_parent_id'), table_name='deletion_jobs')
    op.drop_table('deletion_jobs')
    op.drop_table('activity_versions')
    # ### end Alembic commands ###
